// automatically generated by the FlatBuffers compiler, do not modify

import {flatbuffers} from 'flatbuffers';
/**
 * @enum {number}
 */
export namespace ToServer{
export enum ToServerMsg{
  NONE= 0,
  Handshake= 1
};

export function unionToToServerMsg(
  type: ToServerMsg,
  accessor: (obj:ToServer.Handshake) => ToServer.Handshake|null
): ToServer.Handshake|null {
  switch(ToServer.ToServerMsg[type]) {
    case 'NONE': return null; 
    case 'Handshake': return accessor(new ToServer.Handshake())! as ToServer.Handshake;
    default: return null;
  }
}

export function unionListToToServerMsg(
  type: ToServerMsg, 
  accessor: (index: number, obj:ToServer.Handshake) => ToServer.Handshake|null, 
  index: number
): ToServer.Handshake|null {
  switch(ToServer.ToServerMsg[type]) {
    case 'NONE': return null; 
    case 'Handshake': return accessor(index, new ToServer.Handshake())! as ToServer.Handshake;
    default: return null;
  }
}
}

/**
 * @enum {number}
 */
export namespace ToClient{
export enum ToClientMsg{
  NONE= 0,
  HandshakeAccepted= 1
};

export function unionToToClientMsg(
  type: ToClientMsg,
  accessor: (obj:ToClient.HandshakeAccepted) => ToClient.HandshakeAccepted|null
): ToClient.HandshakeAccepted|null {
  switch(ToClient.ToClientMsg[type]) {
    case 'NONE': return null; 
    case 'HandshakeAccepted': return accessor(new ToClient.HandshakeAccepted())! as ToClient.HandshakeAccepted;
    default: return null;
  }
}

export function unionListToToClientMsg(
  type: ToClientMsg, 
  accessor: (index: number, obj:ToClient.HandshakeAccepted) => ToClient.HandshakeAccepted|null, 
  index: number
): ToClient.HandshakeAccepted|null {
  switch(ToClient.ToClientMsg[type]) {
    case 'NONE': return null; 
    case 'HandshakeAccepted': return accessor(index, new ToClient.HandshakeAccepted())! as ToClient.HandshakeAccepted;
    default: return null;
  }
}
}

/**
 * @constructor
 */
export namespace ToServer{
export class Handshake {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Handshake
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Handshake {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Handshake= obj
 * @returns Handshake
 */
static getRootAsHandshake(bb:flatbuffers.ByteBuffer, obj?:Handshake):Handshake {
  return (obj || new Handshake()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Handshake= obj
 * @returns Handshake
 */
static getSizePrefixedRootAsHandshake(bb:flatbuffers.ByteBuffer, obj?:Handshake):Handshake {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Handshake()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
client():string|null
client(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
client(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
session():string|null
session(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
session(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startHandshake(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset clientOffset
 */
static addClient(builder:flatbuffers.Builder, clientOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, clientOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset sessionOffset
 */
static addSession(builder:flatbuffers.Builder, sessionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, sessionOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHandshake(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createHandshake(builder:flatbuffers.Builder, clientOffset:flatbuffers.Offset, sessionOffset:flatbuffers.Offset):flatbuffers.Offset {
  Handshake.startHandshake(builder);
  Handshake.addClient(builder, clientOffset);
  Handshake.addSession(builder, sessionOffset);
  return Handshake.endHandshake(builder);
}
}
}
/**
 * @constructor
 */
export namespace ToServer{
export class Msg {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Msg
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Msg {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Msg= obj
 * @returns Msg
 */
static getRootAsMsg(bb:flatbuffers.ByteBuffer, obj?:Msg):Msg {
  return (obj || new Msg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Msg= obj
 * @returns Msg
 */
static getSizePrefixedRootAsMsg(bb:flatbuffers.ByteBuffer, obj?:Msg):Msg {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Msg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns ToServer.ToServerMsg
 */
msgType():ToServer.ToServerMsg {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : ToServer.ToServerMsg.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
msg<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startMsg(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param ToServer.ToServerMsg msgType
 */
static addMsgType(builder:flatbuffers.Builder, msgType:ToServer.ToServerMsg) {
  builder.addFieldInt8(0, msgType, ToServer.ToServerMsg.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset msgOffset
 */
static addMsg(builder:flatbuffers.Builder, msgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, msgOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endMsg(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createMsg(builder:flatbuffers.Builder, msgType:ToServer.ToServerMsg, msgOffset:flatbuffers.Offset):flatbuffers.Offset {
  Msg.startMsg(builder);
  Msg.addMsgType(builder, msgType);
  Msg.addMsg(builder, msgOffset);
  return Msg.endMsg(builder);
}
}
}
/**
 * @constructor
 */
export namespace ToClient{
export class HandshakeAccepted {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns HandshakeAccepted
 */
__init(i:number, bb:flatbuffers.ByteBuffer):HandshakeAccepted {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param HandshakeAccepted= obj
 * @returns HandshakeAccepted
 */
static getRootAsHandshakeAccepted(bb:flatbuffers.ByteBuffer, obj?:HandshakeAccepted):HandshakeAccepted {
  return (obj || new HandshakeAccepted()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param HandshakeAccepted= obj
 * @returns HandshakeAccepted
 */
static getSizePrefixedRootAsHandshakeAccepted(bb:flatbuffers.ByteBuffer, obj?:HandshakeAccepted):HandshakeAccepted {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HandshakeAccepted()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Builder builder
 */
static startHandshakeAccepted(builder:flatbuffers.Builder) {
  builder.startObject(0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHandshakeAccepted(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createHandshakeAccepted(builder:flatbuffers.Builder):flatbuffers.Offset {
  HandshakeAccepted.startHandshakeAccepted(builder);
  return HandshakeAccepted.endHandshakeAccepted(builder);
}
}
}
/**
 * @constructor
 */
export namespace ToClient{
export class Msg {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Msg
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Msg {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Msg= obj
 * @returns Msg
 */
static getRootAsMsg(bb:flatbuffers.ByteBuffer, obj?:Msg):Msg {
  return (obj || new Msg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Msg= obj
 * @returns Msg
 */
static getSizePrefixedRootAsMsg(bb:flatbuffers.ByteBuffer, obj?:Msg):Msg {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Msg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns ToClient.ToClientMsg
 */
msgType():ToClient.ToClientMsg {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : ToClient.ToClientMsg.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
msg<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startMsg(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param ToClient.ToClientMsg msgType
 */
static addMsgType(builder:flatbuffers.Builder, msgType:ToClient.ToClientMsg) {
  builder.addFieldInt8(0, msgType, ToClient.ToClientMsg.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset msgOffset
 */
static addMsg(builder:flatbuffers.Builder, msgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, msgOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endMsg(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createMsg(builder:flatbuffers.Builder, msgType:ToClient.ToClientMsg, msgOffset:flatbuffers.Offset):flatbuffers.Offset {
  Msg.startMsg(builder);
  Msg.addMsgType(builder, msgType);
  Msg.addMsg(builder, msgOffset);
  return Msg.endMsg(builder);
}
}
}
